### ISSUE TITLE
Проверка домашнего задания

### ISSUE THREAD

**Issue by Alexnovi2004** [vladdan16/todo_list#2]
Чистота кода и общая структура 

Редми 1/1
Форматирование кода 1/1
Код разбит на фичи и слои 2/2

Верстка + навигация

Верстка двух экранов 10/10
Свайп по айтему логика 3/3
Показ выполненных дел 3/3

Разное

Логгирование 1/2
Иконка приложения 4/4

Варианты итоговой оценки - 25

Рекомендации

Цвет текста выполненной задачи не становится серым

если добавить несколько тасок, потом часть из них сделать выполненными, а потом сделать их назад активными, то при переключении фильтра отображения завершенных тасок, активные таски меняют свой порядок в списке туда и обратно.

Если в каждом классе создавать свой экземпляр логгера, как потом их все конфигурировать из единого места?

Предлагаю добавлять новые таски не в конец списка, а в начало

**Comment by vladdan16** [comment]
Привет! Можешь подсказать, как мне следовало реализовать логирование? Может, есть какие-то образцы?

**Comment by vladdan16** [comment]
Спасибо большое за фидбек! Все это учту в следующей домашке!

**Comment by Alexnovi2004** [comment]
Типа если захочешь добавить туда какие-то фишки, то придется везде прописывать
final logger = Logger(
    printer: PrettyPrinter(
      methodCount: 1,
      lineLength: 50,
      errorMethodCount: 3,
      colors: true,
      printEmojis: true,
    ),
  );
